---
lang: de
title: Spezifikation Unit Metadaten
format:
  html:
    toc: false
    other-links:
        - text: Spezifikation
          href: spec/
---

# Willkommen

Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. 
Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. 